// svelte-version/src/lib/List.svelte
<div class="space-y-2 mt-15">
    <div class="flex space-x-2">
        <label class="flex-1 relative block py-3 px-5 border-2 border-gray-200 rounded-lg bg-white">
            <input
                class="w-full px-0 pb-0 text-lg border-none outline-none focus:ring-0"
                id="name"
                type="text"
                placeholder="Type something"
                on:input={handleInput}
                value={newTodo}
            />
        </label>

        <button type="button" on:click="{addTodo}" class="py-3 px-5 text-lg font-medium text-dark-800 bg-white border border-white rounded-lg focus:outline-none focus:ring">
            Add
        </button>
    </div>

    <ul class="bg-white rounded-lg divide-y divide-y-gray-300 py-3 px-5">
        {#each todos as todo (todo.id)}
            <ListItem todo={todo} on:delete={deleteTodo} on:check={checkTodo}/>
        {/each}
    </ul>
</div>

<script lang="ts">
    import ListItem from "./ListItem.svelte"
    import { v4 as uuidv4 } from "uuid";
    import { onMount } from "svelte";
    import type { Todo } from "../types"

    let todos = [] as Todo[];
    let newTodo = "";

    onMount(() => {
        if(localStorage.getItem("todos") !== null){
            todos = JSON.parse(localStorage.getItem("todos"));
        }
    });    

    const handleInput = (e) => {
        newTodo = e.target.value;
    }

    const saveTodos = () => {
        localStorage.setItem("todos", JSON.stringify(todos));
    }

    const addTodo = () => {
        todos.push({
            id: uuidv4(),
            text: newTodo,
            completed: false
        });

        newTodo = "";

        saveTodos();
    }

    const checkTodo = (e: any) => {
        todos.find((todo) => todo.id === e.detail.id).completed = e.detail.completed;
        saveTodos();
    }

    const deleteTodo = (e: any) => {
        todos = todos.filter((todo: Todo) => todo.id !== e.detail.id);
        saveTodos();
    }
</script>

// vue-version/src/components/List.vue
<template>
    <div space-y-2>
        <div flex space-x-2>
            <label flex-1 relative block py-3 px-5 border-2 border-gray-200 rounded-lg bg-white for="name">
                <input
                    w-full px-0 pt-3.5 pb-0 text-lg border-none outline-none focus="ring-0"
                    id="name"
                    type="text"
                    placeholder="Type something"
                    v-model="newTodo"
                    @key-up.enter="addTodo()"
                />
            </label>

            <button type="button" @click="addTodo()" py-3 px-5 text-lg font-medium text-dark-800 bg-white border border-white rounded-lg focus="outline-none ring">
                Add
            </button>
        </div>

        <ul bg-white rounded-lg divide-y deivide-y-gray-300 py-3 px-5>
            <ListItem v-for="todo in todos" :key="todo.id" :todo="todo" @delete="deleteTodo(todo.id)" />
        </ul>
    </div>
</template>

<script lang="ts" setup>
    const todos = useLocalStorage<Todo[]>("todos", []);

    const newTodo = ref("");

    const addTodo = () => {
        todos.value.push({
            id: uuidv4(),
            text: newTodo.value,
            completed: false
        });

        newTodo.value = "";
    }

    const deleteTodo = (id: string) => {
        todos.value = todos.value.filter((todo: Todo) => todo.id !== id)
    }
</script>
