// svelte-version/src/App.svelte
<script lang="ts">
    import Navbar from "./lib/Navbar.svelte";
    import List from "./lib/List.svelte";
</script>

<div class="flex flex-col min-h-screen">
    <Navbar />

    <div class='grid flex-1 place-content-center'>
        <div class="crate">
            <p class="text-white text-3xl lg:text-7xl font-bold">
                Todo list
            </p>

            <List />
        </div>
    </div>
</div>

// react-version/src/App.tsx
import Navbar from './Navbar';
import HomePage from './HomePage';
import { BrowserRouter as Router, Route, Routes as Switch } from "react-router-dom";
import './App.scss';

function App() {
  return (
    <Router>
        <div className="flex flex-col min-h-screen">
            <Navbar />

            <div className='grid flex-1 place-content-center'>
                <Switch>
                    <Route path="/" element={<HomePage />} />
                </Switch>
            </div>
        </div>
    </Router>
    
  );
}

export default App;
